App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [ username ]
              message: user.username.unique
    properties:
        gender:
            - App\Validator\Constraints\GenderIsValid: ~