App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
            nullable: false
        lastName:
            type: string
            length: 255
            column: last_name
            nullable: true
        username:
            type: string
            length: 255
            nullable: false
            unique: true
        email:
            type: string
            length: 255
            nullable: false
        password:
            type: string
            length: 255
            nullable: false
        gender:
            type: boolean
            nullable: false
        roles:
            type: string
            nullable: false
            options:
                default: "ROLE_USER"